name: Release

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    outputs:
      pr: ${{ steps.release-please.outputs.pr }}
      prs_created: ${{ steps.release-please.outputs.prs_created }}
      version: ${{ steps.release-please.outputs.version }}

    steps:
      - uses: googleapis/release-please-action@v5
        id: release-please
        with:
          config-file: .github/release-please/config.json
          manifest-file: .github/release-please/manifest.json

  prepare-release:
    needs: release-please
    if: needs.release-please.outputs.prs_created == 'true'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ fromJSON(needs.release-please.outputs.pr).headBranchName }}

      - name: Bump version
        run: |
          php ./build/bump.php -v ${{ needs.release-please.outputs.version }}

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: bump v${{ needs.release-please.outputs.version }} on files"
